// File generated by FlutterFire CLI and optimized for Mobile.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'CampusPool is only configured for Android and iOS environments.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOUtne0RfVLxKu0SzXO1-ij-9BACCrrOE',
    appId: '1:903516892507:android:16ee7eb4276bfc369efe7e',
    messagingSenderId: '903516892507',
    projectId: 'campuspool-34f68',
    storageBucket: 'campuspool-34f68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP2uXwXuMqgg7ecQd7gX9jfIgu2_bp8YY',
    appId: '1:903516892507:ios:122f7effaddb44f89efe7e',
    messagingSenderId: '903516892507',
    projectId: 'campuspool-34f68',
    storageBucket: 'campuspool-34f68.firebasestorage.app',
    iosBundleId: 'com.example.campuspool',
  );
}